name: super_profile_card_package
description: "This Flutter package, designed as an artistic masterpiece, enhances the elegance of profile pages by introducing a personalized and attention-grabbing profile card"
version: 0.0.2
homepage: https://github.com/NurhayatYurtaslan/super_profile_card_package
documentation: https://github.com/NurhayatYurtaslan/super_profile_card_package/blob/main/LICENSE

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
